source 'https://rubygems.org'
gem 'rubyzip'
gem 'sinatra'
gem 'github_api'
gem 'thin'
gem 'iami-logger', git: 'https://github.com/IamIpanda/RubyLogger.git'
gem 'ygoruby-data', git: 'https://github.com/IamIpanda/ygoruby-data.git'